import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>bilal ashraf portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <div className="flex space-x-4 items-center w-full p-5 justify-between text-sm text-gray-700">
        <p className="link">home</p>
        <p className="link">projects</p>
        <p className="link">about me</p>
        <p className="link">contact</p>
      </div>

      {/* body */}
      <div className="">
        <h1>welcome to the portfolio of</h1>
        <h1>bilal ashraf</h1>
      </div>

      {/* footer */}
    </div>
  );
}
